name: Build Kernel

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
            build-essential libncurses-dev bison \
            flex libssl-dev libelf-dev bc zip \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            python3 python-is-python3 git wget curl

      - name: Download Sources
        run: |
          git clone https://github.com/dsys1100/zLOS-modified temp -b lineage-20.0 --depth 1
          mv temp/* . && rm -rf temp

      - name: Set Environment
        run: |
          echo "BUILD_TIME=$(date +'%Y%m%d-%H%M')" >> $GITHUB_ENV

      - name: Download Clang r450784d
        run: |
          mkdir tc && wget -qO- \
          https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-release/clang-r450784d.tar.gz \
          | tar -xz -C tc

      - name: Setup KernelSU-Next
        run: |
          curl -LSs \
          https://raw.githubusercontent.com/Sorayukii/KernelSU-Next/stable/kernel/setup.sh \
          | bash -s hookless

      - name: Build Kernel
        run: |
          rm localversion
          export PATH=$PWD/tc/bin:$PATH
          export ARCH=arm64
          export KBUILD_BUILD_USER="dsys1100"
          export KBUILD_BUILD_HOST="GitHubActions"
          ARGS=" O=out ARCH=arm64 CC=clang
          LD=ld.lld AR=llvm-ar NM=llvm-nm STRIP=llvm-strip
          OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump
          CROSS_COMPILE=aarch64-linux-gnu-
          CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          LLVM=1 LLVM_IAS=1
          KCFLAGS="-Wno-unused-but-set-variable"
          "

          echo " "
          echo "Creating config"
          make -s $ARGS mido_defconfig

          echo " "
          echo "Applying custom configs"
          scripts/config --file out/.config \
              --set-str LOCALVERSION "~dsys1100/zLOS-modified" --disable LOCALVERSION_AUTO \
              --enable KSU --enable KSU_TAMPER_SYSCALL_TABLE --enable KSU_EXTRAS

          echo " "
          echo "Building kernel"
          make -s -j$(nproc) $ARGS

      - name: Clone AnyKernel3
        run: |
          git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git AnyKernel3

      - name: Configure AnyKernel3
        run: |
          cat > AnyKernel3/anykernel.sh <<'EOF'
          properties() { '
          kernel.string=zLOS-modified
          do.devicecheck=1
          device.name1=mido
          do.modules=0
          do.systemless=1
          do.cleanup=1
          do.cleanuponabort=0
          '; }
          BLOCK=boot;
          IS_SLOT_DEVICE=0;
          RAMDISK_COMPRESSION=auto;
          PATCH_VBMETA_FLAG=auto;
          . tools/ak3-core.sh
          dump_boot
          write_boot
          EOF

      - name: Create AnyKernel Zip
        run: |
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3/
          if [ -f out/arch/arm64/boot/dtbo.img ]; then
            cp out/arch/arm64/boot/dtbo.img AnyKernel3/
          fi
          cd AnyKernel3
          ZIP_NAME="zLOS-modified-mido-${BUILD_TIME}.zip"
          zip -r9 "$ZIP_NAME" . -x "*.git*" -x "*.zip"
          cd .. && mv AnyKernel3/"$ZIP_NAME" "$ZIP_NAME"
          echo "FINAL_ZIP=$PWD/$ZIP_NAME" >> $GITHUB_ENV

      - name: Create Release Info
        run: |
          echo "WindKernel-Modified" > release_body.txt
          echo "" >> release_body.txt
          echo "Credits:" >> release_body.txt
          echo "Kernel [sources](https://github.com/zeelog/android_kernel_xiaomi_mido) and [author](https://github.com/zeelog/)" >> release_body.txt
        shell: bash

      - name: Create Git Tag and Release with unique name
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "${BUILD_TIME}"
          git push origin "${BUILD_TIME}"
        shell: bash

      - name: Upload Release
        uses: softprops/action-gh-release@master
        with:
          files: ${{ env.FINAL_ZIP }}
          tag_name: ${{ env.BUILD_TIME }}
          draft: false
          body_path: release_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
